### ISSUE TITLE
String value is converted to a number.

### ISSUE THREAD

**Issue by ghassen1433** [mikolajmitura/java-properties-to-json#39]
I want to convert a properties Map to a JSON file:

I have these example: 
"articlenumber": "4711"

the generated JSON is: "articlenumber": 4711,

The 4711 value is a string but the generated value is an integer.

**Comment by mikolajmitura** [comment]
Hello, parser will try convert every string to number if will able to do this. 
String json = new PropertiesToJsonConverter(
            new StringJsonTypeResolver()
    ).parseToJson(properties);
This above code will generate every number as string. 
If you want have mixed type then I need provide a fix. 
Because the design try resolve type from property file and every Map<String, Object> is converted to String<String, String> and next step is a try resolving a types, this might require a design changes. 
Thanks for your issue.

**Comment by mikolajmitura** [comment]
Released 4.0 which solved this issue.
